version: "3.7"
services:
  PostgresDB:
    restart: always
    image: postgres:latest
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=qwerty
      - POSTGRES_DB=postgres
    ports:
      - 5436:5432
  redis:
    image: redislabs/redismod:latest
    ports:
      - 6380:6379
    environment:
      - REDIS_DB=0
  server:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - PostgresDB
      - redis
    networks:
      - default
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/local/go/src/TodoApp
