version: "3.7"
services:
  database:
    image: postgres
    restart: always
    ports:
      - "5436:5432"
    volumes:
      - data:/var/lib/postgresql/data
  server:
    build: ./app
      context: .
      dockerfile: Dockerfile
    depends_on:
      - database
    networks:
      - default
    ports:
      - "8000:8000"
volumes:
  data: