---

is_debug: true
listen:
  type: port
  bind_ip: 0.0.0.0
  port: 8000
postgresqldb:
  host: localhost
  port: 5436
  database: postgres
  username: postgres
  password: qwerty
jwt:
  secret: $3cr3t
redis:
  host: localhost
  port: 6379
  password:
  db: 0

