### Sign-up

POST http://localhost:8000/auth/sign-up
Content-Type: application/json

{
  "name": "German",
  "username": "Bogatov",
  "password": "23Bogatov"
}

### Sign-in
POST http://localhost:8000/auth/sign-in
Content-Type: application/json

{
  "username": "Bogatov",
  "password": "23Bogatov"
}

### create Lists
POST http://localhost:8000/api/lists
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJ1c2VycyIsImV4cCI6MTY2Mjc1NDA0NiwianRpIjoiMSIsInVzZXJuYW1lIjoiQm9nYXRvdiJ9.R4KPo6Jmf4I82IPNCqsL4n_l4TXkXJ0rXxGNepYPtG0

{
  "title": "титил три",
  "description": "описание списка 1321"
}

### get all Lists
GET http://localhost:8000/api/lists
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJ1c2VycyIsImV4cCI6MTY2Mjc0NTY2MCwianRpIjoiMSIsInVzZXJuYW1lIjoiQm9nYXRvdiJ9.phRbHxBRNoESP_RDEu_YPApKAJQZVH03eViCfQBkxAQ

{
}

### get List by id
GET http://localhost:8000/api/lists/3
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJ1c2VycyIsImV4cCI6MTY2Mjc0NTY2MCwianRpIjoiMSIsInVzZXJuYW1lIjoiQm9nYXRvdiJ9.phRbHxBRNoESP_RDEu_YPApKAJQZVH03eViCfQBkxAQ

{
}

### delete List by id
DELETE http://localhost:8000/api/lists/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJ1c2VycyIsImV4cCI6MTY2Mjc0NTY2MCwianRpIjoiMSIsInVzZXJuYW1lIjoiQm9nYXRvdiJ9.phRbHxBRNoESP_RDEu_YPApKAJQZVH03eViCfQBkxAQ

{
}

### update List by id
PUT http://localhost:8000/api/lists/2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJ1c2VycyIsImV4cCI6MTY2Mjc0NTY2MCwianRpIjoiMSIsInVzZXJuYW1lIjoiQm9nYXRvdiJ9.phRbHxBRNoESP_RDEu_YPApKAJQZVH03eViCfQBkxAQ

{
  "title": "измененный заголовок 23!",
  "description": "измененнное описание 23!"
}

### create item
POST http://localhost:8000/api/lists/2/items
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJ1c2VycyIsImV4cCI6MTY2Mjc0NTY2MCwianRpIjoiMSIsInVzZXJuYW1lIjoiQm9nYXRvdiJ9.phRbHxBRNoESP_RDEu_YPApKAJQZVH03eViCfQBkxAQ

{
  "title": "DELETE THIS SHIT",
  "description": "тесуоуй ту"
}

### get all items
GET http://localhost:8000/api/lists/2/items
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJ1c2VycyIsImV4cCI6MTY2Mjc0NTY2MCwianRpIjoiMSIsInVzZXJuYW1lIjoiQm9nYXRvdiJ9.phRbHxBRNoESP_RDEu_YPApKAJQZVH03eViCfQBkxAQ

{
}

### get  item
GET http://localhost:8000/api/items/2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJ1c2VycyIsImV4cCI6MTY2Mjc0NTY2MCwianRpIjoiMSIsInVzZXJuYW1lIjoiQm9nYXRvdiJ9.phRbHxBRNoESP_RDEu_YPApKAJQZVH03eViCfQBkxAQ

{
}

### DELETE  item
DELETE http://localhost:8000/api/items/2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJ1c2VycyIsImV4cCI6MTY2Mjc0NTY2MCwianRpIjoiMSIsInVzZXJuYW1lIjoiQm9nYXRvdiJ9.phRbHxBRNoESP_RDEu_YPApKAJQZVH03eViCfQBkxAQ

{
}

### update item by id
PUT http://localhost:8000/api/items/4
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NTg5Njk5MDEsImlhdCI6MTY1ODkyNjcwMSwidXNlcl9pZCI6MX0.Us737xGRbhzpc3SNuMrC29xz7UDz1Kod1gbJDs1zk7s

{
  "title": "измененный заголовок 23!",
  "description": "измененнное описание 23!"
}